[tool.black]
line-length = 120
# intentionally ignore the generated clients
extend-exclude = '(gooddata-afm-client|gooddata-metadata-client|gooddata-scan-client|.*\.snapshot\..*)'

[tool.isort]
# make isort setup compatible with black
profile = "black"
multi_line_output = 3
include_trailing_comma = true
line_length = 120
skip_glob = ["*/gooddata-afm-client/*","*/gooddata-metadata-client/*","*/gooddata-scan-client/*", "*/.snapshot/*"]
src_paths = [
    "gooddata-afm-client",
    "gooddata-metadata-client",
    "gooddata-scan-client",
    "gooddata-sdk",
    "gooddata-fdw",
    "gooddata-pandas"
]
