# (C) 2021 GoodData Corporation
#

version: '3.7'

services:
  gooddata-cn-ce:
    # dev_latest tag represents weekly builds, which may be unstable.
    # Feel free to use stable releases represented by tags like 1.5.0
    image: gooddata/gooddata-cn-ce:dev_latest
    ports:
      - "3000:3000"
      - "5432:5432"
    volumes:
      - gooddata-cn-ce-data:/data
    environment:
      LICENSE_AND_PRIVACY_POLICY_ACCEPTED: "YES"
      APP_LOGLEVEL: "INFO"

  gooddata-fdw:
    build:
      context: ../
      dockerfile: gooddata-fdw/Dockerfile
    ports:
      - "2543:5432"
    environment:
      POSTGRES_DB: gooddata
      POSTGRES_USER: gooddata
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-gooddata123}"
    command: ["postgres", "-c", "shared_preload_libraries=foreign_table_exposer", "-c", "log_statement=all", "-c", "client_min_messages=DEBUG1", "-c", "log_min_messages=DEBUG1"]

volumes:
  gooddata-cn-ce-data:
